name: Create pull request from feature to main

on:
    push:
        branches:
            - feat/*
            - fix/*
            - refactor/*
            - test/*
            - ci/*

jobs:
    create-pr:
        runs-on: ubuntu-latest
        name: Create pull request from feature branch to main
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Create pull request
              id: 'cpr'
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main

            - name: Check outputs
              if: ${{ steps.cpr.outputs.pull-request-number }}
              run: |
                  echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
                  echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
