name: Create pull request from feature to main

on:
    push:
        branches:
            - feat/*
            - fix/*
            - refactor/*
            - test/*
            - ci/*

jobs:
    create-pr:
        runs-on: ubuntu-latest
        name: Create pull request from feature branch to main
        steps:
            - name: Detect changes between source and release
              id: 'detect-changes-between-source-and-release-branch'
              uses: fjenik/detect-changes-between-two-branches@0.0.3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  target-branch: main
                  source-branch: ${{ github.ref_name }}

            - name: Detect changes output
              run: echo "Output of detect changes ${{ steps.detect-changes-between-source-and-release-branch.outputs.is-source-branch-ahead }}"

            - name: Check if pr already exists
              id: 'check-if-pr-already-exists'
              if: ${{ steps.detect-changes-between-source-and-release-branch.output.is-source-branch-ahead == 'true' }}
              uses: fjenik/check-if-pr-exists@0.0.3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  target-branch: main
                  source-branch: ${{ github.ref_name }}
