name: Feature

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    check-health:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install deps
              run: npm ci

            - name: Run tests
              run: npm run test
